### ISSUE TITLE
 'copyGridToArrayReal' is not defined

### ISSUE THREAD

**Issue by MillyaPC** [RachelCmy/den2vel#2]
When generating datasets, the error " 'copyGridToArrayXXX' is not defined" is raised.
Where can i find this function :)

**Comment by RachelCmy** [comment]
It is a Mantaflow function that copies fluid grids to NumPy arrays.
Is the option, "-DNUMPY", enabled when compiling Mantaflow?

```
# compile Mantaflow
mkdir mantaflow/build
cd mantaflow/build
# GUI is optional
cmake .. -DGUI=OFF -DOPENMP=ON -DNUMPY=ON
```

**Comment by MillyaPC** [comment]
thx :)
