### ISSUE TITLE
Encountered a problem while running

### ISSUE THREAD

**Issue by OliverLai** [RachelCmy/den2vel#3]
When I configured the environment, then an error occurred.
"File './test/scene_obs_test_ir.py', line 372, in <module>
copyGridToArrayInt(target=sl_arf, source=sl_flags)
NameError: name 'copyGridToArrayInt' is not defined."
How can I resolve this problem?

**Comment by RachelCmy** [comment]
this may be relevant: https://github.com/RachelCmy/den2vel/issues/2#issuecomment-903137006

**Comment by OliverLai** [comment]
Thank you for your reply, but after I followed the above steps again, the error also occurred again.
